const regions: { id: number; value: string }[] = [
  { id: 1, value: "Buenos Aires" },
  { id: 2, value: "Catamarca" },
  { id: 3, value: "Chaco" },
  { id: 4, value: "Chubut" },
  { id: 5, value: "Ciudad Autónoma de Buenos Aires" },
  { id: 6, value: "Córdoba" },
  { id: 7, value: "Corrientes" },
  { id: 8, value: "Entre Ríos" },
  { id: 9, value: "Formosa" },
  { id: 10, value: "Jujuy" },
  { id: 11, value: "La Pampa" },
  { id: 12, value: "La Rioja" },
  { id: 13, value: "Mendoza" },
  { id: 14, value: "Misiones" },
  { id: 15, value: "Neuquén" },
  { id: 16, value: "Río Negro" },
  { id: 17, value: "Salta" },
  { id: 18, value: "San Juan" },
  { id: 19, value: "San Luis" },
  { id: 20, value: "Santa Cruz" },
  { id: 21, value: "Santa Fe" },
  { id: 22, value: "Santiago del Estero" },
  { id: 23, value: "Tierra del Fuego, Antártida e Islas del Atlántico Sur" },
  { id: 24, value: "Tucumán" },
]

export default regions
